version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/aws-cicd-demo

hooks:
  BeforeInstall:
    - location: scripts/deploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy/application_start.sh
      timeout: 300
      runas: root