version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Starting build process...
      # テストに必要な場合のみ一時的に依存関係をインストール
      - npm ci --no-production
      - chmod +x scripts/*.sh
  build:
    commands:
      - echo Running tests...
      - npm test || echo "No tests specified"
      - echo Running linting...
      - npm run lint || echo "No linting configured"
  post_build:
    commands:
      - echo Build completed on `date`
      # デプロイ前に一時的な node_modules を削除
      - rm -rf node_modules

artifacts:
  files:
    - app.js
    - package.json
    - package-lock.json
    - appspec.yml
    - scripts/**/*
  discard-paths: no